---
title: X-Cart 5 Developer Documentation
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: daemos@x-cart.com
description: X-Cart is the free shopping cart software & solutions for high‑performing
  online stores
baseurl: ''
url: http://devs.x-cart.com
encoding: utf-8
repository: xcart/xc5-docs
ga_code: UA-56346543-1
safe: false
markdown: kramdown
incremental: false
lsi: true
kramdown:
  input: GFM
index_path: links.xml
search:
  preferred: devs.x-cart.com
cse:
  host: kbsearch.x-cart.com
  path: search
gems:
- jekyll-redirect-from
paginate_count: 5
paginate_path: "/en/what_is_new/page:num/"
lang_default: en
lang:
  en: English
  ru: Russian
sort_default: order
sorts:
  changelog: updated_at
category_pr:
  changelog: 0.2
