# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: X-Cart 5 Knowledge Base
email: daemos@x-cart.com
description: X-Cart is the free shopping cart software & solutions for high‑performing online stores
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kb5.x-cart.com" # the base hostname & protocol for your site
encoding: utf-8
repository: xcart/xc5-docs

# Build settings
safe: false
markdown: kramdown
incremental: false
lsi: true

index_path: "links.xml"

elasticsearch:
    host: "localhost:9200"
    index: "knowledgebase"
    type: "articles"

gems:
  - jekyll-redirect-from

# Languages

lang_default: en
lang:
    en: English
    ru: Russian

# Translations
