# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: X-Cart 5 Development
email: daemos@xcart.com
description: X-Cart is the free shopping cart software & solutions for high‑performing online stores
baseurl: "/xc5-docs" # the subpath of your site, e.g. /blog
url: "http://drdaemos.github.io" # the base hostname & protocol for your site
twitter_username: drdaemos
github_username:  drdaemos
encoding: utf-8

# Build settings
markdown: kramdown
incremental: false
lsi: true

gems:
  - jekyll-redirect-from

# Languages

baseurl_lang: ''
lang_current: ''
lang_default: en
lang:
    en: English
    ru: Russian

# Translations
